name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'

      - name: Ant Build
        run: ant -noinput -buildfile build.xml
